// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Zk7ejWZ-gkCI7rLH9uyJI-qI-YJ6woQ',
    appId: '1:243377899178:web:6a739785b8771a9a50f2d3',
    messagingSenderId: '243377899178',
    projectId: 'thrim-b55f7',
    authDomain: 'thrim-b55f7.firebaseapp.com',
    storageBucket: 'thrim-b55f7.appspot.com',
    measurementId: 'G-17TB4814TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFGDuB0f2qUYUnn362_n8rNKDoAJG0SMU',
    appId: '1:243377899178:android:1a8ebf870615bd5050f2d3',
    messagingSenderId: '243377899178',
    projectId: 'thrim-b55f7',
    storageBucket: 'thrim-b55f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ppMlBiycV6Vx5_SkTpbfjH5R1MlXUec',
    appId: '1:243377899178:ios:ca4bf315aa371dc850f2d3',
    messagingSenderId: '243377899178',
    projectId: 'thrim-b55f7',
    storageBucket: 'thrim-b55f7.appspot.com',
    androidClientId: '243377899178-jhma419c3tr0bl7gprs9upvoslq66a9i.apps.googleusercontent.com',
    iosClientId: '243377899178-ha63bn74jtjpl7jvfgihlu9qma8uqnp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myContent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ppMlBiycV6Vx5_SkTpbfjH5R1MlXUec',
    appId: '1:243377899178:ios:ca4bf315aa371dc850f2d3',
    messagingSenderId: '243377899178',
    projectId: 'thrim-b55f7',
    storageBucket: 'thrim-b55f7.appspot.com',
    androidClientId: '243377899178-jhma419c3tr0bl7gprs9upvoslq66a9i.apps.googleusercontent.com',
    iosClientId: '243377899178-ha63bn74jtjpl7jvfgihlu9qma8uqnp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myContent',
  );
}
